version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    network_mode: "host"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017
      - DB_NAME=leamss
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=https://api.leamss.com
    restart: always
    ports:
      - "3000:80"

volumes:
  mongo_data:


