"""Phase 19.7 — Assessing Authorities AU seed list.

Source: 26 bodies observed in DB + 13 canonical bodies referenced by DEWR/Home Affairs
        (https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-assessment/assessing-authorities)
        — fetched via curl HTTP 200 but page is SPA + Akamai WAF blocks headless rendering.
        Fallback: web-search-confirmed canon list (Feb 2026, 39 approved bodies).

All bodies seeded with status="draft" — admin verifies via Phase 19.9 UI before active.
Fees + processing times are best-known published rates as of Feb 2026 (admin can edit later).
"""
from __future__ import annotations
from typing import Any, Dict, List


# Default placeholders — admin should override per body via Phase 19.9 UI
_DEFAULT_PROCESSING = {"standard_days_min": 60, "standard_days_max": 90, "priority_days_min": None, "priority_days_max": None, "notes": "Verify with authority"}
_DEFAULT_FEES = {"msa_fee_aud": None, "rpl_fee_aud": None, "skill_review_fee_aud": None, "appeal_fee_aud": None, "additional_fees": [], "payment_methods": ["credit_card"], "currency": "AUD"}


AU_AUTHORITIES: List[Dict[str, Any]] = [
    # ───── TIER 1: Heavy hitters (>20 occupations each) ─────
    {
        "code": "VETASSESS",
        "full_name": "Vocational Education and Training Assessment Services",
        "aliases": ["VETASSESS", "vetassess", "VET Assessment Services", "vetassess.com.au"],
        "website": "https://www.vetassess.com.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "priority_days_min": 10, "priority_days_max": 20, "notes": "Priority assessment available at additional cost"},
        "fees": {"msa_fee_aud": 1188, "rpl_fee_aud": 800, "skill_review_fee_aud": 350, "appeal_fee_aud": 700, "additional_fees": [{"name": "Priority Processing", "amount_aud": 814}], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "VETASSESS is the largest assessing authority for professional and trade occupations in Australia. Evaluates qualifications + employment for migration purposes.",
        "documents_required_common": [
            "Passport bio-data page (colour scan)",
            "Official Degree / Diploma Certificate",
            "Full Academic Transcripts for all completed qualifications",
            "Formal Statement of Service on company letterhead (with duties, hours & dates)",
            "Payment evidence (payslips, tax returns, bank statements for all claimed periods)",
            "Organisational Chart on company letterhead (for Managerial / Group A occupations)",
            "Detailed Professional CV / Résumé",
            "Official English translations for any non-English documents",
        ],
    },
    {
        "code": "TRA",
        "full_name": "Trades Recognition Australia",
        "aliases": ["TRA", "tra", "Trades Recognition Australia"],
        "website": "https://www.tradesrecognitionaustralia.gov.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 120, "priority_days_min": None, "priority_days_max": None, "notes": "Offshore Skills Assessment Program (OSAP) for trades"},
        "fees": {"msa_fee_aud": 1107, "rpl_fee_aud": 1107, "skill_review_fee_aud": 350, "appeal_fee_aud": 350, "additional_fees": [], "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "TRA is the federal government body responsible for skills assessment in 600+ trade occupations.",
        "documents_required_common": [
            "Passport bio-data page (colour copy)",
            "Trade Qualification / Apprenticeship Certificate or equivalent",
            "Detailed Statement of Service from employers listing specific trade tasks & tools used",
            "Proof of paid employment (minimum 3 pieces of pay evidence per year claimed)",
            "Workplace logbook / Job descriptions / Tool checklists",
            "Current resume / CV with detailed trade history",
        ],
    },
    {
        "code": "ACS",
        "full_name": "Australian Computer Society Incorporated",
        "aliases": ["ACS", "acs", "Australian Computer Society", "Australian Computer Society Incorporated"],
        "website": "https://www.acs.org.au/",
        "processing": {"standard_days_min": 56, "standard_days_max": 84, "priority_days_min": 7, "priority_days_max": 14, "notes": "ACS Fast-Track ($1,200 extra)"},
        "fees": {"msa_fee_aud": 625, "rpl_fee_aud": 625, "skill_review_fee_aud": 423, "appeal_fee_aud": 423, "additional_fees": [{"name": "Fast-Track Processing", "amount_aud": 1200}], "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 24,
        "methodology_summary": "ACS is the assessing authority for ICT occupations under 26 ANZSCO codes. Evaluates degree + ICT employment.",
        "documents_required_common": [
            "Passport bio-data page",
            "Degree / Diploma Certificate & Transcripts with detailed ICT subject syllabus",
            "Employer Reference Letters with at least 65% relevant ICT duties and project tasks",
            "Evidence of paid employment (tax assessment notices, payslips, bank statements)",
            "Statutory Declaration or Affidavit (if employer reference cannot be obtained)",
            "Vendor certifications (e.g. Microsoft, Cisco, AWS if applicable for RPL)",
            "Detailed CV / Résumé",
        ],
    },
    {
        "code": "MedBA",
        "full_name": "Medical Board of Australia",
        "aliases": ["MedBA", "medba", "Medical Board of Australia", "Medical Board", "MBA"],
        "website": "https://www.medicalboard.gov.au/",
        "processing": {"standard_days_min": 90, "standard_days_max": 180, "priority_days_min": None, "priority_days_max": None, "notes": "Specialist pathway via AMC/specialty colleges"},
        "fees": {"msa_fee_aud": 1200, "rpl_fee_aud": None, "skill_review_fee_aud": None, "appeal_fee_aud": None, "additional_fees": [{"name": "AMC MCQ Exam", "amount_aud": 2880}, {"name": "AMC Clinical Exam", "amount_aud": 3950}], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 24,
        "methodology_summary": "MedBA registers medical practitioners. Migration applicants typically need AMC assessment + specialty college approval.",
        "documents_required_common": [
            "Passport bio-data page",
            "Primary Medical Degree (MBBS / MD / equivalent)",
            "EPIC Primary Source Verification (ECFMG / AMC portfolio)",
            "Internship Completion Certificate",
            "Certificate of Good Standing from home country medical council",
            "AMC MCQ and Clinical Examination score reports (if applicable)",
            "English language test scorecard (IELTS 7.0 / OET B / PTE 65)",
        ],
    },
    {
        "code": "EA",
        "full_name": "The Institution of Engineers Australia",
        "aliases": ["EA", "Engineers Australia", "The Institution of Engineers Australia", "Institution of Engineers Australia", "engineers_australia", "engineersaustralia"],
        "website": "https://www.engineersaustralia.org.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "priority_days_min": 10, "priority_days_max": 20, "notes": "Fast-Track ($1,000 AUD extra)"},
        "fees": {"msa_fee_aud": 720, "rpl_fee_aud": 720, "skill_review_fee_aud": 480, "appeal_fee_aud": 480, "additional_fees": [{"name": "Fast-Track Processing", "amount_aud": 1000}], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "EA assesses engineering qualifications via CDR (Competency Demonstration Report) or accredited pathway. Categories: Professional Engineer, Engineering Technologist, Engineering Associate.",
        "documents_required_common": [
            "Passport bio-data page (colour copy)",
            "Engineering Degree Certificate & Academic Transcripts",
            "Competency Demonstration Report (CDR) — 3 distinct Career Episodes",
            "Summary Statement cross-referencing CDR episodes to EA competency units",
            "Continuing Professional Development (CPD) statement list",
            "English language test result (IELTS 6.0 in all bands or PTE 50 in each)",
            "Official Reference Letters on company letterhead & Proof of paid employment",
            "Comprehensive CV / Résumé",
        ],
    },
    {
        "code": "ANMAC",
        "full_name": "Australian Nursing and Midwifery Accreditation Council Limited",
        "aliases": ["ANMAC", "anmac", "Australian Nursing and Midwifery Accreditation Council", "Australian Nursing & Midwifery Accreditation Council"],
        "website": "https://www.anmac.org.au/",
        "processing": {"standard_days_min": 56, "standard_days_max": 84, "priority_days_min": None, "priority_days_max": None, "notes": "Includes English language verification"},
        "fees": {"msa_fee_aud": 525, "rpl_fee_aud": 525, "skill_review_fee_aud": 250, "appeal_fee_aud": 700, "additional_fees": [], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ANMAC is the migration assessing authority for nursing and midwifery occupations. Different from NMBA (registration).",
        "documents_required_common": [
            "Passport bio-data page (colour scan)",
            "Nursing / Midwifery Degree / Diploma Certificate & Transcripts",
            "Current Professional Nursing Registration / Practicing Certificate from home country",
            "Verification of Registration Certificate directly sent from regulatory council",
            "English language test report (IELTS 7.0 all bands / OET B all bands / PTE 65 all bands)",
            "Professional Reference Letters from nurse unit managers verifying 3+ months practice",
        ],
    },
    # ───── TIER 2: Mid-volume (5-20 occupations) ─────
    {
        "code": "IML",
        "full_name": "Institute of Managers and Leaders National",
        "aliases": ["IML", "iml", "Institute of Managers and Leaders", "Institute of Managers and Leaders National"],
        "website": "https://managersandleaders.com.au/",
        "processing": _DEFAULT_PROCESSING,
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 870},
        "validity_period_months": 36,
        "methodology_summary": "IML assesses management occupations under ANZSCO Major Group 1.",
        "documents_required_common": [
            "Passport bio-data page",
            "Higher education degree certificates & transcripts",
            "Company Organisational Chart showing your managerial position and subordinate staff",
            "Detailed Statement of Service on letterhead outlining senior management responsibilities",
            "Budget management and strategic KPI achievement records",
            "Comprehensive Executive CV / Résumé",
        ],
    },
    {
        "code": "AITSL",
        "full_name": "Australian Institute for Teaching and School Leadership Limited",
        "aliases": ["AITSL", "aitsl", "Australian Institute for Teaching and School Leadership"],
        "website": "https://www.aitsl.edu.au/",
        "processing": {"standard_days_min": 56, "standard_days_max": 84, "priority_days_min": None, "priority_days_max": None, "notes": "English language requirements apply"},
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 815, "skill_review_fee_aud": 200},
        "validity_period_months": 36,
        "methodology_summary": "AITSL is the migration assessing authority for primary/secondary teacher occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Teaching Degree Certificate (minimum 4 years full-time higher education)",
            "Academic Transcripts showing at least 45 days of supervised teaching practice",
            "Official letter from university confirming completion of supervised teaching practicum",
            "Academic IELTS test report (Listening 8.0, Speaking 8.0, Reading 7.0, Writing 7.0)",
            "Teaching Registration from home jurisdiction (if applicable)",
        ],
    },
    {
        "code": "CWA",
        "full_name": "Community Work Australia Limited",
        "aliases": ["CWA", "Community Work Australia", "Community Work Australia Limited"],
        "website": "https://www.communityworkaustralia.com.au/",
        "processing": _DEFAULT_PROCESSING,
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 950},
        "validity_period_months": 36,
        "methodology_summary": "CWA (formerly AASW) assesses social work and community service occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Community work / Human services degree certificate and transcripts",
            "Evidence of 500+ hours of direct fieldwork placement during study",
            "Employer reference letters verifying paid community service experience",
            "Detailed CV / Résumé",
        ],
    },
    {
        "code": "CAANZ",
        "full_name": "Chartered Accountants Australia and New Zealand",
        "aliases": ["CAANZ", "caanz", "Chartered Accountants ANZ", "Chartered Accountants Australia and New Zealand"],
        "website": "https://www.charteredaccountantsanz.com/",
        "processing": _DEFAULT_PROCESSING,
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 555},
        "validity_period_months": 36,
        "methodology_summary": "CAANZ is one of three assessing authorities for accountant migration (with CPA Australia and IPA).",
        "documents_required_common": [
            "Passport bio-data page",
            "University Degree / Master's Certificate & Complete Transcripts",
            "Syllabus / Course descriptor of all accounting and finance subjects studied",
            "English language proficiency test report (Academic IELTS 7.0 each or PTE 65 each)",
            "Detailed Statement of Service & payslips (for Skilled Employment Assessment)",
        ],
    },
    # ───── TIER 3: Specialty bodies (1-4 occupations each) ─────
    {
        "code": "AMSA",
        "full_name": "Australian Maritime Safety Authority",
        "aliases": ["AMSA", "Australian Maritime Safety Authority"],
        "website": "https://www.amsa.gov.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Maritime qualification verification"},
        "fees": {"msa_fee_aud": 450, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AMSA assesses maritime occupations (Ship's Master, Deck Officer, Marine Engineer, etc.).",
        "documents_required_common": [
            "Passport bio-data page (colour copy)",
            "Certificate of Competency (CoC) / Maritime qualification",
            "Continuous Discharge Certificate (CDC) / Seafarer Service Book",
            "Detailed sea service testimonials on company letterhead",
            "STCW (Standards of Training, Certification and Watchkeeping) certificates",
            "Valid Maritime Medical Fitness Certificate",
            "Detailed maritime CV / résumé",
        ],
    },
    {
        "code": "APS",
        "full_name": "Australian Psychological Society Limited",
        "aliases": ["APS", "Australian Psychological Society"],
        "website": "https://psychology.org.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Assessment of overseas psychology qualifications"},
        "fees": {"msa_fee_aud": 880, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "APS assesses psychologist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "4-year or 6-year accredited Psychology Degree / Master's / Doctorate Certificate",
            "Official Academic Transcripts with course syllabus details",
            "Thesis / Dissertation abstract and supervisor confirmation",
            "Proof of home country psychologist registration / licence",
            "English language test report (Academic IELTS 7.0 in all bands or PTE 65)",
            "Detailed psychology CV / Résumé",
        ],
    },
    {
        "code": "ACECQA",
        "full_name": "Australian Children's Education and Care Quality Authority",
        "aliases": ["ACECQA", "Australian Children's Education and Care Quality"],
        "website": "https://www.acecqa.gov.au/",
        "processing": {"standard_days_min": 45, "standard_days_max": 70, "notes": "Early childhood teaching qualifications"},
        "fees": {"msa_fee_aud": 1170, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ACECQA assesses early childhood education occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Early Childhood Teaching Degree Certificate (minimum 4-year Bachelor or Master of Teaching)",
            "Official Academic Transcripts for all completed units",
            "Supervised Professional Experience Evidence confirming at least 45 days with children aged 0-8",
            "Proof of English Language Proficiency (Academic IELTS 7.0+ or English study exemption)",
            "Professional Teaching Résumé / CV",
        ],
    },
    {
        "code": "ASMIRT",
        "full_name": "Australian Society of Medical Imaging and Radiation Therapy",
        "aliases": ["ASMIRT", "Australian Society of Medical Imaging and Radiation Therapy", "Australian Society of Medical Imagery and Radiation Therapy"],
        "website": "https://www.asmirt.org/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Radiographer and Sonographer skills assessment"},
        "fees": {"msa_fee_aud": 1100, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ASMIRT assesses medical imaging and radiation therapy occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Medical Radiation Science / Radiography / Nuclear Medicine Degree & Transcripts",
            "Clinical placement logbook / Supervised clinical hours verification",
            "Home country radiography registration licence and Certificate of Good Standing",
            "Radiation safety licence & Evidence of Continuing Professional Development (CPD)",
            "English Language Test Certificate (IELTS 7.0 / OET B / PTE 65)",
        ],
    },
    {
        "code": "AIMS",
        "full_name": "Australian Institute of Medical Scientists",
        "aliases": ["AIMS", "Australian Institute of Medical Scientists"],
        "website": "https://www.aims.org.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Medical Laboratory Scientist assessment"},
        "fees": {"msa_fee_aud": 950, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AIMS assesses medical laboratory scientist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Medical Laboratory Science / Pathology Degree Certificate & Transcripts",
            "Detailed subject curriculum covering biochemistry, haematology, microbiology, transfusion, and histopathology",
            "Minimum 2 years full-time diagnostic medical laboratory experience reference letters",
            "AIMS Professional Examination Results (if required by pathway)",
            "English language test scorecard (IELTS 7.0 / PTE 65)",
        ],
    },
    {
        "code": "CMBA",
        "full_name": "Chinese Medicine Board of Australia",
        "aliases": ["CMBA", "Chinese Medicine Board of Australia"],
        "website": "https://www.chinesemedicineboard.gov.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "notes": "Acupuncturist and Chinese herbal medicine practitioner assessment"},
        "fees": {"msa_fee_aud": 850, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "CMBA registers Chinese medicine practitioners.",
        "documents_required_common": [
            "Passport bio-data page",
            "Chinese Medicine / Acupuncture Degree Certificate & Transcripts",
            "Evidence of minimum 900 hours of supervised clinical training",
            "Certificate of Good Standing from home country regulatory authority",
            "English language test report (IELTS 7.0 / OET B)",
        ],
    },
    {
        "code": "NAATI",
        "full_name": "National Accreditation Authority for Translators and Interpreters Ltd",
        "aliases": ["NAATI", "National Accreditation Authority for Translators and Interpreters"],
        "website": "https://www.naati.com.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Credentialed Community Language & translation skills assessment"},
        "fees": {"msa_fee_aud": 875, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "NAATI assesses translator and interpreter occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Translation / Interpreting Degree or Diploma Certificate & Transcripts",
            "NAATI Certification Test / Credentialed Community Language (CCL) test results",
            "Proof of professional translation / interpreting practice hours",
            "Detailed translation CV / work portfolio",
        ],
    },
    {
        "code": "CASA",
        "full_name": "Civil Aviation Safety Authority",
        "aliases": ["CASA", "Civil Aviation Safety Authority"],
        "website": "https://www.casa.gov.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Pilot and air traffic controller licence assessment"},
        "fees": {"msa_fee_aud": 650, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "CASA regulates aviation occupations (Air Traffic Controller, Aeronautical Engineer, etc.).",
        "documents_required_common": [
            "Passport bio-data page",
            "Commercial Pilot Licence (CPL) / Airline Transport Pilot Licence (ATPL) or Air Traffic Control Licence",
            "Certified Flying Logbook showing flight hours by aircraft category/class",
            "Class 1 Aviation Medical Certificate",
            "Aviation English Language Proficiency (AELP) Level 6 Certification",
        ],
    },
    {
        "code": "ADC",
        "full_name": "Australian Dental Council Limited",
        "aliases": ["ADC", "Australian Dental Council"],
        "website": "https://www.adc.org.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Initial assessment of overseas dental qualifications"},
        "fees": {"msa_fee_aud": 640, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ADC assesses dentistry occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Bachelor of Dental Surgery (BDS / DDS) Degree Certificate",
            "Detailed Dental Transcripts showing clinical course hours",
            "Certificate of Good Standing from home Dental Council (valid within 3 months)",
            "ADC Written Examination and Practical Examination Results",
            "English language scorecard (IELTS 7.0 in all bands / OET B in all components)",
        ],
    },
    {
        "code": "APharmC",
        "full_name": "Australian Pharmacy Council Limited",
        "aliases": ["APharmC", "Australian Pharmacy Council"],
        "website": "https://www.pharmacycouncil.org.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Eligibility check and examination stream"},
        "fees": {"msa_fee_aud": 1340, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "APharmC assesses pharmacist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Bachelor / Master of Pharmacy Degree Certificate & Transcripts",
            "Current Pharmacist Registration / Practicing Licence from home country",
            "Letter of Good Standing from Pharmacy Council",
            "KAPS (Knowledge Assessment of Pharmaceutical Sciences) Examination Results",
            "English language test scorecard (IELTS 7.5 / OET A/B / PTE 70)",
        ],
    },
    {
        "code": "DAA",
        "full_name": "Dietitians Association of Australia",
        "aliases": ["DAA", "Dietitians Association of Australia"],
        "website": "https://dietitiansaustralia.org.au/",
        "processing": {"standard_days_min": 45, "standard_days_max": 75, "notes": "Dietetic Skills Recognition (DSR) Stage 1 assessment"},
        "fees": {"msa_fee_aud": 1250, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "DAA assesses dietitian occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Nutrition & Dietetics Degree Certificate & Transcripts",
            "Evidence of minimum 20 weeks of supervised clinical and community dietetic placements",
            "Dietetic Skills Recognition (DSR) Stage 1 Written Examination result",
            "English language scorecard (IELTS 7.0 / OET B)",
        ],
    },
    {
        "code": "PodBA",
        "full_name": "Podiatry Board of Australia",
        "aliases": ["PodBA", "Podiatry Board of Australia"],
        "website": "https://www.podiatryboard.gov.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "notes": "Overseas podiatrist qualification assessment"},
        "fees": {"msa_fee_aud": 850, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "PodBA registers podiatrists.",
        "documents_required_common": [
            "Passport bio-data page",
            "Podiatry Degree Certificate & Academic Transcripts",
            "Evidence of supervised clinical hours in podiatric medicine",
            "Home country Podiatry Board Registration & Good Standing Certificate",
            "English language test report (IELTS 7.0 / OET B / PTE 65)",
        ],
    },
    {
        "code": "OTC",
        "full_name": "Occupational Therapy Council of Australia Limited",
        "aliases": ["OTC", "Occupational Therapy Council of Australia"],
        "website": "https://www.otcouncil.com.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Stage 1 Desktop Assessment"},
        "fees": {"msa_fee_aud": 1200, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "OTC assesses occupational therapist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "WFOT-approved Occupational Therapy Degree Certificate & Transcripts",
            "Official confirmation of 1000+ hours of supervised clinical fieldwork",
            "Home country OT registration licence & Certificate of Good Standing",
            "Stage 1 Desktop Assessment documentation & Supervised Practice Plan",
        ],
    },
    {
        "code": "APC",
        "full_name": "Australian Physiotherapy Council Limited",
        "aliases": ["APC", "Australian Physiotherapy Council"],
        "website": "https://physiocouncil.com.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Interim Certificate / Initial Assessment"},
        "fees": {"msa_fee_aud": 1210, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "APC assesses physiotherapist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Physiotherapy Degree Certificate & Academic Transcripts",
            "Clinical practice logbook documenting hours in cardiorespiratory, musculoskeletal, and neurological physiotherapy",
            "Home country registration certificate & Good Standing Certificate",
            "APC Interim Certificate / Clinical Assessment documentation",
            "English language scorecard (IELTS 7.0 / OET B)",
        ],
    },
    {
        "code": "AIQS",
        "full_name": "The Australian Institute of Quantity Surveyors",
        "aliases": ["AIQS", "The Australian Institute of Quantity Surveyors"],
        "website": "https://www.aiqs.com.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Skilled Migration Assessment for Quantity Surveyors"},
        "fees": {"msa_fee_aud": 850, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AIQS assesses quantity surveyor occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Bachelor's Degree in Quantity Surveying / Construction Economics & Transcripts",
            "Project list and syllabus breakdown of estimating, cost planning, and contract administration",
            "Detailed Employer Reference Letters detailing quantity surveying duties",
            "Proof of paid employment (tax records, payslips, bank statements)",
            "Detailed QS Professional CV / Résumé",
        ],
    },
    # ───── TIER 4: Complex legacy / state-level umbrella ─────
    {
        "code": "LAA",
        "full_name": "Legal admissions authority of a state or territory",
        "aliases": ["Legal admissions authority of a state or territory", "Legal admissions authority", "LAA"],
        "website": "https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-assessment/assessing-authorities",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "State Legal Admissions Board academic evaluation"},
        "fees": {"msa_fee_aud": 550, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "Umbrella reference covering state-level legal admission bodies (NSW Law Society, Victorian Legal Admissions Board, etc.). Admin may split into separate entities via Phase 19.9 UI.",
        "documents_required_common": [
            "Passport bio-data page",
            "Law Degree (LLB / JD) Certificate & Academic Transcripts",
            "Course descriptors for Priestly 11 core legal subjects",
            "Certificate of Admission / Practicing Certificate (if admitted as lawyer/advocate)",
            "Certificate of Good Standing from home Bar Council / Law Society",
        ],
        "_complex_legacy": True,
    },
    # ───── TIER 5: Canonical missing (not in DB but per DEWR 39-body list) ─────
    {
        "code": "CPA",
        "full_name": "CPA Australia",
        "aliases": ["CPA", "CPA Australia"],
        "website": "https://www.cpaaustralia.com.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Accounting qualifications assessment"},
        "fees": {"msa_fee_aud": 530, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "CPA Australia assesses accountant migration (with CAANZ and IPA).",
        "documents_required_common": [
            "Passport bio-data page",
            "Accounting Degree / Master's Certificate & Complete Transcripts",
            "Course syllabus covering mandatory accounting competency areas",
            "English language test scorecard (IELTS 7.0 in all bands or PTE 65 in each band)",
            "Detailed Statement of Service & payslips (for Skilled Employment Assessment)",
            "Professional membership certificates (if applicable)",
        ],
    },
    {
        "code": "IPA",
        "full_name": "Institute of Public Accountants",
        "aliases": ["IPA", "Institute of Public Accountants"],
        "website": "https://www.publicaccountants.org.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Accounting skills and degree assessment"},
        "fees": {"msa_fee_aud": 430, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "IPA is one of three assessing authorities for accountant migration.",
        "documents_required_common": [
            "Passport bio-data page",
            "University Degree in Accounting / Commerce & Transcripts",
            "Subject descriptors covering mandatory accounting core units",
            "English language scorecard (IELTS Academic 7.0 or PTE Academic 65)",
            "Employer reference letters and paid employment evidence",
        ],
    },
    {
        "code": "AMC",
        "full_name": "Australian Medical Council",
        "aliases": ["AMC", "Australian Medical Council"],
        "website": "https://www.amc.org.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 120, "notes": "Primary Source Verification + AMC Portfolio"},
        "fees": {"msa_fee_aud": 600, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 24,
        "methodology_summary": "AMC assesses medical practitioners via MCQ + clinical exam pathway.",
        "documents_required_common": [
            "Passport bio-data page",
            "Primary Medical Qualification (MBBS / MD)",
            "EPIC Primary Source Verification Portfolio",
            "12-month Rotatory Internship Completion Certificate",
            "Certificate of Good Standing from Medical Board",
            "AMC Part 1 MCQ & Part 2 Clinical Examination results",
        ],
    },
    {
        "code": "AHPRA",
        "full_name": "Australian Health Practitioner Regulation Agency",
        "aliases": ["AHPRA", "Australian Health Practitioner Regulation Agency"],
        "website": "https://www.ahpra.gov.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "notes": "Health practitioner registration eligibility"},
        "fees": {"msa_fee_aud": 850, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AHPRA administers registration for 16 regulated health professions.",
        "documents_required_common": [
            "Passport bio-data page",
            "Recognized Health Practitioner Qualification Certificate & Transcripts",
            "Verification of Registration from overseas licensing authority",
            "Criminal history check & Good Standing Certificate",
            "English language test report (IELTS 7.0 / PTE 65)",
        ],
    },
    {
        "code": "AACA",
        "full_name": "Architects Accreditation Council of Australia",
        "aliases": ["AACA", "Architects Accreditation Council of Australia"],
        "website": "https://www.aaca.org.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Overseas Qualifications Assessment (OQA)"},
        "fees": {"msa_fee_aud": 1150, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AACA assesses architect occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "5-year Professional Architecture Degree / Master's Certificate & Transcripts",
            "Comprehensive Academic Portfolio of student architectural design projects",
            "Syllabus documentation for design, technology, professional practice, and history",
            "AACA Overseas Qualifications Assessment (OQA) documentation",
            "Detailed Architectural CV / Résumé",
        ],
    },
    {
        "code": "RACS",
        "full_name": "Royal Australasian College of Surgeons",
        "aliases": ["RACS", "Royal Australasian College of Surgeons"],
        "website": "https://www.surgeons.org/",
        "processing": {"standard_days_min": 60, "standard_days_max": 120, "notes": "Specialist surgeon international assessment"},
        "fees": {"msa_fee_aud": 3200, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "RACS assesses surgeon specialist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Specialist Surgical Qualification & Medical Degree",
            "Logbook of surgical operations performed (surgeon and assistant)",
            "Primary source verification of surgical qualifications via EPIC / AMC",
            "Certificate of Good Standing from home surgical college / medical board",
            "Surgical references from 3 consultant surgeons",
        ],
    },
    {
        "code": "RACGP",
        "full_name": "Royal Australian College of General Practitioners",
        "aliases": ["RACGP", "Royal Australian College of General Practitioners"],
        "website": "https://www.racgp.org.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 120, "notes": "Comparability assessment for GPs"},
        "fees": {"msa_fee_aud": 2800, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "RACGP assesses general practitioner specialist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Primary Medical Degree & Specialist General Practice Qualification",
            "EPIC Primary Source Verification",
            "Evidence of 4+ years full-time general practice experience",
            "Certificate of Good Standing from medical licensing authority",
            "RACGP Comparability Assessment application portfolio",
        ],
    },
    {
        "code": "RANZCP",
        "full_name": "Royal Australian and New Zealand College of Psychiatrists",
        "aliases": ["RANZCP", "Royal Australian and New Zealand College of Psychiatrists"],
        "website": "https://www.ranzcp.org/",
        "processing": {"standard_days_min": 60, "standard_days_max": 120, "notes": "Specialist assessment for psychiatrists"},
        "fees": {"msa_fee_aud": 3100, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "RANZCP assesses psychiatrist specialist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Medical Degree & Specialist Psychiatry Qualification",
            "EPIC verification portfolio",
            "Psychiatry training curriculum & logbook of clinical rotations",
            "Certificate of Good Standing from medical council",
            "References from supervising consultant psychiatrists",
        ],
    },
    {
        "code": "NMBA",
        "full_name": "Nursing and Midwifery Board of Australia",
        "aliases": ["NMBA", "Nursing and Midwifery Board of Australia"],
        "website": "https://www.nursingmidwiferyboard.gov.au/",
        "processing": {"standard_days_min": 45, "standard_days_max": 75, "notes": "Overseas qualified nurse registration"},
        "fees": {"msa_fee_aud": 850, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "NMBA registers nurses and midwives (different from ANMAC migration assessment).",
        "documents_required_common": [
            "Passport bio-data page",
            "Nursing / Midwifery Qualification Certificate & Transcripts",
            "Overseas registration certificate & Good Standing Certificate directly from council",
            "Evidence of meeting NMBA English language requirements (IELTS 7.0 / OET B)",
            "Proof of continuous professional practice (minimum 450 hours in last 5 years)",
        ],
    },
    {
        "code": "OCANZ",
        "full_name": "Optometry Council of Australia and New Zealand",
        "aliases": ["OCANZ", "Optometry Council of Australia and New Zealand", "OptmA"],
        "website": "https://www.ocanz.org/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Competency assessment in optometry"},
        "fees": {"msa_fee_aud": 1100, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "OCANZ assesses optometrist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Optometry Degree Certificate & Academic Transcripts",
            "Evidence of supervised clinical practice hours",
            "Certificate of Good Standing from home Optometry Board",
            "OCANZ Competency Examination (Written & Clinical) Results",
            "English language test scorecard (IELTS 7.0 / OET B)",
        ],
    },
    {
        "code": "AVBC",
        "full_name": "Australasian Veterinary Boards Council",
        "aliases": ["AVBC", "Australasian Veterinary Boards Council"],
        "website": "https://www.avbc.asn.au/",
        "processing": {"standard_days_min": 40, "standard_days_max": 60, "notes": "Veterinary skills assessment"},
        "fees": {"msa_fee_aud": 800, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AVBC assesses veterinarian occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Veterinary Science Degree Certificate & Transcripts",
            "Home country veterinary registration / license & Good Standing Certificate",
            "National Veterinary Examination (NVE) Preliminary and Clinical results",
            "English language scorecard (IELTS 7.0 in all bands)",
        ],
    },
    {
        "code": "MARA",
        "full_name": "Office of the Migration Agents Registration Authority",
        "aliases": ["MARA", "Office of the Migration Agents Registration Authority", "OMARA"],
        "website": "https://www.mara.gov.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Migration agent registration assessment"},
        "fees": {"msa_fee_aud": 450, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "MARA regulates migration agent occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Graduate Diploma in Australian Migration Law and Practice / Law Degree",
            "Capstone Assessment Results",
            "National Police Check / Background Clearance Certificate",
            "Professional Indemnity Insurance policy certificate",
        ],
    },
    {
        "code": "ISNSW",
        "full_name": "Institution of Surveyors NSW",
        "aliases": ["ISNSW", "Institution of Surveyors NSW", "SARB"],
        "website": "https://www.surveyors.org.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Surveyor qualifications assessment"},
        "fees": {"msa_fee_aud": 950, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ISNSW assesses surveyor occupations (took over from GCA in 2026).",
        "documents_required_common": [
            "Passport bio-data page",
            "4-year Surveying Degree Certificate & Academic Transcripts",
            "Detailed syllabus coverage in geodesy, cadastral surveying, GIS, and photogrammetry",
            "Practical Surveying Logbook and project portfolio",
            "Statements of Service verifying post-qualification surveying practice",
            "Professional Surveying CV",
        ],
    },
    # ───── TIER 6: Bodies surfaced during Phase 19.7 migration ─────
    {
        "code": "ANZSNM",
        "full_name": "Australian and New Zealand Society of Nuclear Medicine",
        "aliases": ["ANZSNM", "Australian and New Zealand Society of Nuclear Medicine"],
        "website": "https://www.anzsnm.org.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Nuclear medicine technologist assessment"},
        "fees": {"msa_fee_aud": 1050, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ANZSNM assesses nuclear medicine technologist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Nuclear Medicine Technology Degree & Transcripts",
            "Supervised clinical placement hours logbook",
            "Radiation safety licence & Registration from home country",
            "English language scorecard (IELTS 7.0 / PTE 65)",
        ],
    },
    {
        "code": "AOPA",
        "full_name": "Australian Orthotic Prosthetic Association Limited",
        "aliases": ["AOPA", "Australian Orthotic Prosthetic Association", "Australian Orthotic Prosthetic Association Limited"],
        "website": "https://www.aopa.org.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Orthotist and prosthetist overseas assessment"},
        "fees": {"msa_fee_aud": 900, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AOPA assesses orthotist and prosthetist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Orthotics & Prosthetics Degree Certificate & Transcripts",
            "Supervised clinical hours logbook (minimum 1000 hours)",
            "Certificate of Good Standing from professional association",
            "Comprehensive clinical portfolio and case studies",
        ],
    },
    {
        "code": "AOAC",
        "full_name": "Australasian Osteopathic Accreditation Council Limited",
        "aliases": ["AOAC", "Australasian Osteopathic Accreditation Council", "Australasian Osteopathic Accreditation Council Limited"],
        "website": "https://www.osteopathiccouncil.org.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Osteopath overseas qualification assessment"},
        "fees": {"msa_fee_aud": 1100, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AOAC assesses osteopath occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Osteopathy Degree / Master's Certificate & Transcripts",
            "Clinical training logbook (minimum 1000 hours of clinical contact)",
            "Certificate of Good Standing from Osteopathy Board",
            "AOAC Stage 1 Desktop & Stage 2 Examination Results",
        ],
    },
    {
        "code": "SPA",
        "full_name": "The Speech Pathology Association of Australia Limited",
        "aliases": ["SPA", "Speech Pathology Association of Australia", "The Speech Pathology Association of Australia Limited"],
        "website": "https://www.speechpathologyaustralia.org.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Speech pathologist mutual recognition & assessment"},
        "fees": {"msa_fee_aud": 1050, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "SPA assesses speech pathologist occupations.",
        "documents_required_common": [
            "Passport bio-data page",
            "Speech Pathology / Speech-Language Therapy Degree & Transcripts",
            "Evidence of minimum 300 hours of supervised clinical placements",
            "Certificate of Good Standing from home speech pathology association",
            "Detailed case studies and clinical competence portfolio",
        ],
    },
    {
        "code": "AASW",
        "full_name": "Australian Association of Social Workers Limited",
        "aliases": ["AASW", "Australian Association of Social Workers", "Australian Association of Social Workers Limited"],
        "website": "https://www.aasw.asn.au/",
        "processing": {"standard_days_min": 30, "standard_days_max": 60, "notes": "Social worker migration skills assessment"},
        "fees": {"msa_fee_aud": 980, "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "AASW assesses social worker occupations (sometimes paired with CWA).",
        "documents_required_common": [
            "Passport bio-data page",
            "Accredited Social Work Degree (minimum 4-year Bachelor or Master of Social Work)",
            "Academic Transcripts verifying minimum 980 hours of supervised direct field education across 2 distinct placement settings",
            "Evidence of human services / social work curriculum content",
            "Academic IELTS test report (minimum 7.0 in all 4 components)",
            "Detailed Social Work CV / Résumé",
        ],
    },
]


async def ensure_seeded_in_db(db):
    """Idempotently seed and ensure assessing authorities collection in MongoDB."""
    import uuid
    from datetime import datetime, timezone

    coll = db["assessing_authorities"]
    occ_coll = db["occupation_master"]
    now = datetime.now(timezone.utc).isoformat()

    for body in AU_AUTHORITIES:
        code = body["code"]
        existing = await coll.find_one({"code": code})
        occ_count = 0
        if existing and existing.get("id"):
            occ_count = await occ_coll.count_documents({"country_code": "AU", "assessing_authority_id": existing["id"]})

        doc = {
            **body,
            "country": "AU",
            "country_code": "AU",
            "status": existing.get("status") if existing else "active",
            "source_url": "https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-assessment/assessing-authorities",
            "last_updated_at": now,
            "occupation_count": occ_count,
            "documents_required_common": body.get("documents_required_common") or (existing.get("documents_required_common") if existing else None) or [
                "Passport bio-data page (colour copy)",
                "Official Degree / Diploma certificates",
                "Full Academic Transcripts for all years",
                "Detailed CV / Résumé",
                "Statement of Service / Employer Reference Letters on official letterhead",
                "Proof of paid employment (payslips, tax documents, bank statements)",
                "English language test report (IELTS / PTE / TOEFL)",
            ],
        }
        if existing:
            await coll.update_one({"code": code}, {"$set": doc})
        else:
            doc["id"] = str(uuid.uuid4())
            doc["created_at"] = now
            await coll.insert_one(doc)


def get_canonical_codes() -> List[str]:
    """List of canonical codes seeded — used by tests + admin UI."""
    return [b["code"] for b in AU_AUTHORITIES]
