"""Phase 19.7 — Assessing Authorities AU seed list.

Source: 26 bodies observed in DB + 13 canonical bodies referenced by DEWR/Home Affairs
        (https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-assessment/assessing-authorities)
        — fetched via curl HTTP 200 but page is SPA + Akamai WAF blocks headless rendering.
        Fallback: web-search-confirmed canon list (Feb 2026, 39 approved bodies).

All bodies seeded with status="draft" — admin verifies via Phase 19.9 UI before active.
Fees + processing times are best-known published rates as of Feb 2026 (admin can edit later).
"""
from __future__ import annotations
from typing import Any, Dict, List


# Default placeholders — admin should override per body via Phase 19.9 UI
_DEFAULT_PROCESSING = {"standard_days_min": 60, "standard_days_max": 90, "priority_days_min": None, "priority_days_max": None, "notes": "Verify with authority"}
_DEFAULT_FEES = {"msa_fee_aud": None, "rpl_fee_aud": None, "skill_review_fee_aud": None, "appeal_fee_aud": None, "additional_fees": [], "payment_methods": ["credit_card"], "currency": "AUD"}


AU_AUTHORITIES: List[Dict[str, Any]] = [
    # ───── TIER 1: Heavy hitters (>20 occupations each) ─────
    {
        "code": "VETASSESS",
        "full_name": "Vocational Education and Training Assessment Services",
        "aliases": ["VETASSESS", "vetassess", "VET Assessment Services", "vetassess.com.au"],
        "website": "https://www.vetassess.com.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "priority_days_min": 10, "priority_days_max": 20, "notes": "Priority assessment available at additional cost"},
        "fees": {"msa_fee_aud": 1188, "rpl_fee_aud": 800, "skill_review_fee_aud": 350, "appeal_fee_aud": 700, "additional_fees": [{"name": "Priority Processing", "amount_aud": 814}], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "VETASSESS is the largest assessing authority for professional and trade occupations in Australia. Evaluates qualifications + employment for migration purposes.",
    },
    {
        "code": "TRA",
        "full_name": "Trades Recognition Australia",
        "aliases": ["TRA", "tra", "Trades Recognition Australia"],
        "website": "https://www.tradesrecognitionaustralia.gov.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 120, "priority_days_min": None, "priority_days_max": None, "notes": "Offshore Skills Assessment Program (OSAP) for trades"},
        "fees": {"msa_fee_aud": 1107, "rpl_fee_aud": 1107, "skill_review_fee_aud": 350, "appeal_fee_aud": 350, "additional_fees": [], "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "TRA is the federal government body responsible for skills assessment in 600+ trade occupations.",
    },
    {
        "code": "ACS",
        "full_name": "Australian Computer Society Incorporated",
        "aliases": ["ACS", "acs", "Australian Computer Society", "Australian Computer Society Incorporated"],
        "website": "https://www.acs.org.au/",
        "processing": {"standard_days_min": 56, "standard_days_max": 84, "priority_days_min": 7, "priority_days_max": 14, "notes": "ACS Fast-Track ($1,200 extra)"},
        "fees": {"msa_fee_aud": 625, "rpl_fee_aud": 625, "skill_review_fee_aud": 423, "appeal_fee_aud": 423, "additional_fees": [{"name": "Fast-Track Processing", "amount_aud": 1200}], "payment_methods": ["credit_card"], "currency": "AUD"},
        "validity_period_months": 24,
        "methodology_summary": "ACS is the assessing authority for ICT occupations under 26 ANZSCO codes. Evaluates degree + ICT employment.",
    },
    {
        "code": "MedBA",
        "full_name": "Medical Board of Australia",
        "aliases": ["MedBA", "medba", "Medical Board of Australia", "Medical Board", "MBA"],
        "website": "https://www.medicalboard.gov.au/",
        "processing": {"standard_days_min": 90, "standard_days_max": 180, "priority_days_min": None, "priority_days_max": None, "notes": "Specialist pathway via AMC/specialty colleges"},
        "fees": {"msa_fee_aud": 1200, "rpl_fee_aud": None, "skill_review_fee_aud": None, "appeal_fee_aud": None, "additional_fees": [{"name": "AMC MCQ Exam", "amount_aud": 2880}, {"name": "AMC Clinical Exam", "amount_aud": 3950}], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 24,
        "methodology_summary": "MedBA registers medical practitioners. Migration applicants typically need AMC assessment + specialty college approval.",
    },
    {
        "code": "EA",
        "full_name": "The Institution of Engineers Australia",
        "aliases": ["EA", "Engineers Australia", "The Institution of Engineers Australia", "Institution of Engineers Australia", "engineers_australia", "engineersaustralia"],
        "website": "https://www.engineersaustralia.org.au/",
        "processing": {"standard_days_min": 60, "standard_days_max": 90, "priority_days_min": 10, "priority_days_max": 20, "notes": "Fast-Track ($1,000 AUD extra)"},
        "fees": {"msa_fee_aud": 720, "rpl_fee_aud": 720, "skill_review_fee_aud": 480, "appeal_fee_aud": 480, "additional_fees": [{"name": "Fast-Track Processing", "amount_aud": 1000}], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "EA assesses engineering qualifications via CDR (Competency Demonstration Report) or accredited pathway. Categories: Professional Engineer, Engineering Technologist, Engineering Associate.",
    },
    {
        "code": "ANMAC",
        "full_name": "Australian Nursing and Midwifery Accreditation Council Limited",
        "aliases": ["ANMAC", "anmac", "Australian Nursing and Midwifery Accreditation Council", "Australian Nursing & Midwifery Accreditation Council"],
        "website": "https://www.anmac.org.au/",
        "processing": {"standard_days_min": 56, "standard_days_max": 84, "priority_days_min": None, "priority_days_max": None, "notes": "Includes English language verification"},
        "fees": {"msa_fee_aud": 525, "rpl_fee_aud": 525, "skill_review_fee_aud": 250, "appeal_fee_aud": 700, "additional_fees": [], "payment_methods": ["credit_card", "bank_transfer"], "currency": "AUD"},
        "validity_period_months": 36,
        "methodology_summary": "ANMAC is the migration assessing authority for nursing and midwifery occupations. Different from NMBA (registration).",
    },
    # ───── TIER 2: Mid-volume (5-20 occupations) ─────
    {
        "code": "IML",
        "full_name": "Institute of Managers and Leaders National",
        "aliases": ["IML", "iml", "Institute of Managers and Leaders", "Institute of Managers and Leaders National"],
        "website": "https://managersandleaders.com.au/",
        "processing": _DEFAULT_PROCESSING,
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 870},
        "validity_period_months": 36,
        "methodology_summary": "IML assesses management occupations under ANZSCO Major Group 1.",
    },
    {
        "code": "AITSL",
        "full_name": "Australian Institute for Teaching and School Leadership Limited",
        "aliases": ["AITSL", "aitsl", "Australian Institute for Teaching and School Leadership"],
        "website": "https://www.aitsl.edu.au/",
        "processing": {"standard_days_min": 56, "standard_days_max": 84, "priority_days_min": None, "priority_days_max": None, "notes": "English language requirements apply"},
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 815, "skill_review_fee_aud": 200},
        "validity_period_months": 36,
        "methodology_summary": "AITSL is the migration assessing authority for primary/secondary teacher occupations.",
    },
    {
        "code": "CWA",
        "full_name": "Community Work Australia Limited",
        "aliases": ["CWA", "Community Work Australia", "Community Work Australia Limited"],
        "website": "https://www.communityworkaustralia.com.au/",
        "processing": _DEFAULT_PROCESSING,
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 950},
        "validity_period_months": 36,
        "methodology_summary": "CWA (formerly AASW) assesses social work and community service occupations.",
    },
    {
        "code": "CAANZ",
        "full_name": "Chartered Accountants Australia and New Zealand",
        "aliases": ["CAANZ", "caanz", "Chartered Accountants ANZ", "Chartered Accountants Australia and New Zealand"],
        "website": "https://www.charteredaccountantsanz.com/",
        "processing": _DEFAULT_PROCESSING,
        "fees": {**_DEFAULT_FEES, "msa_fee_aud": 555},
        "validity_period_months": 36,
        "methodology_summary": "CAANZ is one of three assessing authorities for accountant migration (with CPA Australia and IPA).",
    },
    # ───── TIER 3: Specialty bodies (1-4 occupations each) ─────
    {"code": "AMSA", "full_name": "Australian Maritime Safety Authority",
     "aliases": ["AMSA", "Australian Maritime Safety Authority"], "website": "https://www.amsa.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AMSA assesses maritime occupations (Ship's Master, Deck Officer, Marine Engineer, etc.)."},
    {"code": "APS", "full_name": "Australian Psychological Society Limited",
     "aliases": ["APS", "Australian Psychological Society"], "website": "https://psychology.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": {**_DEFAULT_FEES, "msa_fee_aud": 880}, "validity_period_months": 36,
     "methodology_summary": "APS assesses psychologist occupations."},
    {"code": "ACECQA", "full_name": "Australian Children's Education and Care Quality Authority",
     "aliases": ["ACECQA", "Australian Children's Education and Care Quality"], "website": "https://www.acecqa.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "ACECQA assesses early childhood education occupations."},
    {"code": "ASMIRT", "full_name": "Australian Society of Medical Imaging and Radiation Therapy",
     "aliases": ["ASMIRT", "Australian Society of Medical Imaging and Radiation Therapy", "Australian Society of Medical Imagery and Radiation Therapy"], "website": "https://www.asmirt.org/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "ASMIRT assesses medical imaging and radiation therapy occupations."},
    {"code": "AIMS", "full_name": "Australian Institute of Medical Scientists",
     "aliases": ["AIMS", "Australian Institute of Medical Scientists"], "website": "https://www.aims.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AIMS assesses medical laboratory scientist occupations."},
    {"code": "CMBA", "full_name": "Chinese Medicine Board of Australia",
     "aliases": ["CMBA", "Chinese Medicine Board of Australia"], "website": "https://www.chinesemedicineboard.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "CMBA registers Chinese medicine practitioners."},
    {"code": "NAATI", "full_name": "National Accreditation Authority for Translators and Interpreters Ltd",
     "aliases": ["NAATI", "National Accreditation Authority for Translators and Interpreters"], "website": "https://www.naati.com.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "NAATI assesses translator and interpreter occupations."},
    {"code": "CASA", "full_name": "Civil Aviation Safety Authority",
     "aliases": ["CASA", "Civil Aviation Safety Authority"], "website": "https://www.casa.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "CASA regulates aviation occupations (Air Traffic Controller, Aeronautical Engineer, etc.)."},
    {"code": "ADC", "full_name": "Australian Dental Council Limited",
     "aliases": ["ADC", "Australian Dental Council"], "website": "https://www.adc.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "ADC assesses dentistry occupations."},
    {"code": "APharmC", "full_name": "Australian Pharmacy Council Limited",
     "aliases": ["APharmC", "Australian Pharmacy Council"], "website": "https://www.pharmacycouncil.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "APharmC assesses pharmacist occupations."},
    {"code": "DAA", "full_name": "Dietitians Association of Australia",
     "aliases": ["DAA", "Dietitians Association of Australia"], "website": "https://dietitiansaustralia.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "DAA assesses dietitian occupations."},
    {"code": "PodBA", "full_name": "Podiatry Board of Australia",
     "aliases": ["PodBA", "Podiatry Board of Australia"], "website": "https://www.podiatryboard.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "PodBA registers podiatrists."},
    {"code": "OTC", "full_name": "Occupational Therapy Council of Australia Limited",
     "aliases": ["OTC", "Occupational Therapy Council of Australia"], "website": "https://www.otcouncil.com.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "OTC assesses occupational therapist occupations."},
    {"code": "APC", "full_name": "Australian Physiotherapy Council Limited",
     "aliases": ["APC", "Australian Physiotherapy Council"], "website": "https://physiocouncil.com.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "APC assesses physiotherapist occupations."},
    {"code": "AIQS", "full_name": "The Australian Institute of Quantity Surveyors",
     "aliases": ["AIQS", "The Australian Institute of Quantity Surveyors"], "website": "https://www.aiqs.com.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AIQS assesses quantity surveyor occupations."},
    # ───── TIER 4: Complex legacy / state-level umbrella ─────
    {
        "code": "LAA",
        "full_name": "Legal admissions authority of a state or territory",
        "aliases": ["Legal admissions authority of a state or territory", "Legal admissions authority", "LAA"],
        "website": "https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-assessment/assessing-authorities",
        "processing": _DEFAULT_PROCESSING,
        "fees": _DEFAULT_FEES,
        "validity_period_months": 36,
        "methodology_summary": "Umbrella reference covering state-level legal admission bodies (NSW Law Society, Victorian Legal Admissions Board, etc.). Admin may split into separate entities via Phase 19.9 UI.",
        "_complex_legacy": True,
    },
    # ───── TIER 5: Canonical missing (not in DB but per DEWR 39-body list) ─────
    {"code": "CPA", "full_name": "CPA Australia",
     "aliases": ["CPA", "CPA Australia"], "website": "https://www.cpaaustralia.com.au/",
     "processing": _DEFAULT_PROCESSING, "fees": {**_DEFAULT_FEES, "msa_fee_aud": 530}, "validity_period_months": 36,
     "methodology_summary": "CPA Australia assesses accountant migration (with CAANZ and IPA)."},
    {"code": "IPA", "full_name": "Institute of Public Accountants",
     "aliases": ["IPA", "Institute of Public Accountants"], "website": "https://www.publicaccountants.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": {**_DEFAULT_FEES, "msa_fee_aud": 430}, "validity_period_months": 36,
     "methodology_summary": "IPA is one of three assessing authorities for accountant migration."},
    {"code": "AMC", "full_name": "Australian Medical Council",
     "aliases": ["AMC", "Australian Medical Council"], "website": "https://www.amc.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 24,
     "methodology_summary": "AMC assesses medical practitioners via MCQ + clinical exam pathway."},
    {"code": "AHPRA", "full_name": "Australian Health Practitioner Regulation Agency",
     "aliases": ["AHPRA", "Australian Health Practitioner Regulation Agency"], "website": "https://www.ahpra.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AHPRA administers registration for 16 regulated health professions."},
    {"code": "AACA", "full_name": "Architects Accreditation Council of Australia",
     "aliases": ["AACA", "Architects Accreditation Council of Australia"], "website": "https://www.aaca.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AACA assesses architect occupations."},
    {"code": "RACS", "full_name": "Royal Australasian College of Surgeons",
     "aliases": ["RACS", "Royal Australasian College of Surgeons"], "website": "https://www.surgeons.org/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "RACS assesses surgeon specialist occupations."},
    {"code": "RACGP", "full_name": "Royal Australian College of General Practitioners",
     "aliases": ["RACGP", "Royal Australian College of General Practitioners"], "website": "https://www.racgp.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "RACGP assesses general practitioner specialist occupations."},
    {"code": "RANZCP", "full_name": "Royal Australian and New Zealand College of Psychiatrists",
     "aliases": ["RANZCP", "Royal Australian and New Zealand College of Psychiatrists"], "website": "https://www.ranzcp.org/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "RANZCP assesses psychiatrist specialist occupations."},
    {"code": "NMBA", "full_name": "Nursing and Midwifery Board of Australia",
     "aliases": ["NMBA", "Nursing and Midwifery Board of Australia"], "website": "https://www.nursingmidwiferyboard.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "NMBA registers nurses and midwives (different from ANMAC migration assessment)."},
    {"code": "OCANZ", "full_name": "Optometry Council of Australia and New Zealand",
     "aliases": ["OCANZ", "Optometry Council of Australia and New Zealand", "OptmA"], "website": "https://www.ocanz.org/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "OCANZ assesses optometrist occupations."},
    {"code": "AVBC", "full_name": "Australasian Veterinary Boards Council",
     "aliases": ["AVBC", "Australasian Veterinary Boards Council"], "website": "https://www.avbc.asn.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AVBC assesses veterinarian occupations."},
    {"code": "MARA", "full_name": "Office of the Migration Agents Registration Authority",
     "aliases": ["MARA", "Office of the Migration Agents Registration Authority", "OMARA"], "website": "https://www.mara.gov.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "MARA regulates migration agent occupations."},
    {"code": "ISNSW", "full_name": "Institution of Surveyors NSW",
     "aliases": ["ISNSW", "Institution of Surveyors NSW", "SARB"], "website": "https://www.surveyors.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "ISNSW assesses surveyor occupations (took over from GCA in 2026)."},
    # ───── TIER 6: Bodies surfaced during Phase 19.7 migration ─────
    # Placeholder fees/processing — admin must verify via Phase 19.9 UI (UI shows amber "Needs Review" chip).
    {"code": "ANZSNM", "full_name": "Australian and New Zealand Society of Nuclear Medicine",
     "aliases": ["ANZSNM", "Australian and New Zealand Society of Nuclear Medicine"], "website": "https://www.anzsnm.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "ANZSNM assesses nuclear medicine technologist occupations.",
     "_seed_quality": "placeholder"},
    {"code": "AOPA", "full_name": "Australian Orthotic Prosthetic Association Limited",
     "aliases": ["AOPA", "Australian Orthotic Prosthetic Association", "Australian Orthotic Prosthetic Association Limited"], "website": "https://www.aopa.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AOPA assesses orthotist and prosthetist occupations.",
     "_seed_quality": "placeholder"},
    {"code": "AOAC", "full_name": "Australasian Osteopathic Accreditation Council Limited",
     "aliases": ["AOAC", "Australasian Osteopathic Accreditation Council", "Australasian Osteopathic Accreditation Council Limited"], "website": "https://www.osteopathiccouncil.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AOAC assesses osteopath occupations.",
     "_seed_quality": "placeholder"},
    {"code": "SPA", "full_name": "The Speech Pathology Association of Australia Limited",
     "aliases": ["SPA", "Speech Pathology Association of Australia", "The Speech Pathology Association of Australia Limited"], "website": "https://www.speechpathologyaustralia.org.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "SPA assesses speech pathologist occupations.",
     "_seed_quality": "placeholder"},
    {"code": "AASW", "full_name": "Australian Association of Social Workers Limited",
     "aliases": ["AASW", "Australian Association of Social Workers", "Australian Association of Social Workers Limited"], "website": "https://www.aasw.asn.au/",
     "processing": _DEFAULT_PROCESSING, "fees": _DEFAULT_FEES, "validity_period_months": 36,
     "methodology_summary": "AASW assesses social worker occupations (sometimes paired with CWA).",
     "_seed_quality": "placeholder"},
]


def get_canonical_codes() -> List[str]:
    """List of canonical codes seeded — used by tests + admin UI."""
    return [b["code"] for b in AU_AUTHORITIES]
